{% set name = "oci" %}
{% set version = "2.89.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oci-{{ version }}.tar.gz
  sha256: 83e8f88aca2c6dc03432b935314b1b95e5234ee2401ce02747aa6545731d0e42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi
    - cryptography >=3.2.1,<=39.0.0
    - pyopenssl >=17.5.0,<=22.1.0
    - python-dateutil >=2.5.3,<3.0.0
    - pytz >=2016.10
    - circuitbreaker >=1.3.1,<2.0.0

test:
  imports:
    - oci
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.oracle.com/en-us/iaas/tools/python/latest/index.html
  summary: Oracle Cloud Infrastructure Python SDK
  license: Apache-2.0 OR UPL-1.0
  license_file: LICENSE.txt
  dev_url: https://github.com/oracle/oci-python-sdk

extra:
  recipe-maintainers:
    - manics
